import 'package:app_mobile/model/level_item.dart';

class MapData {
  final String background;
  final List<LevelItem> levels;

  const MapData({
    required this.background,
    required this.levels,
  });
}

const List<MapData> gameMaps = [
  MapData(
    background: 'assets/images/game_map/map_1.jpg',
    levels: [
      LevelItem(
        number: 1,
        title: 'Greeting',
        x: 0.72,
        y: 0.89,
        status: LevelStatus.completed,
        levelStar: LevelStar.excellent,
      ),
      LevelItem(
        number: 2,
        title: 'Number',
        x: 0.30,
        y: 0.87,
        status: LevelStatus.completed,
        levelStar: LevelStar.great,
      ),
      LevelItem(
        number: 3,
        title: 'Number',
        x: 0.42,
        y: 0.76,
        status: LevelStatus.completed,
        levelStar: LevelStar.good,
      ),
      LevelItem(
        number: 4,
        title: 'Family',
        x: 0.70,
        y: 0.68,
        status: LevelStatus.unlocked,
      ),
      LevelItem(
        number: 5,
        title: 'Greeting',
        x: 0.15,
        y: 0.69,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 6,
        title: 'Number',
        x: 0.35,
        y: 0.61,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 7,
        title: 'Number',
        x: 0.72,
        y: 0.56,
        status: LevelStatus.special,
        shape: LevelButtonShape.pill,
      ),
      LevelItem(
        number: 8,
        title: 'Family',
        x: 0.24,
        y: 0.52,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 9,
        title: 'Greeting',
        x: 0.52,
        y: 0.44,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 10,
        title: 'Number',
        x: 0.80,
        y: 0.37,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 11,
        title: 'Number',
        x: 0.48,
        y: 0.29,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 12,
        title: 'Family',
        x: 0.89,
        y: 0.24,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 13,
        title: 'Greeting',
        x: 0.27,
        y: 0.24,
        shape: LevelButtonShape.pill,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 14,
        title: 'Number',
        x: 0.35,
        y: 0.10,
        status: LevelStatus.locked,
        showLock: true,
      ),
    ],
  ),
  MapData(
    background: 'assets/images/game_map/map_2.jpg',
    levels: [
      LevelItem(
        number: 1,
        title: 'Greeting',
        x: 0.60,
        y: 0.88,
        status: LevelStatus.completed,
        levelStar: LevelStar.excellent,
      ),
      LevelItem(
        number: 2,
        title: 'Number',
        x: 0.35,
        y: 0.82,
        status: LevelStatus.completed,
        levelStar: LevelStar.great,
      ),
      LevelItem(
        number: 3,
        title: 'Number',
        x: 0.49,
        y: 0.76,
        status: LevelStatus.completed,
        levelStar: LevelStar.good,
      ),
      LevelItem(
        number: 4,
        title: 'Family',
        x: 0.78,
        y: 0.70,
        status: LevelStatus.unlocked,
        shape: LevelButtonShape.roundedSquare,
      ),
      LevelItem(
        number: 5,
        title: 'Greeting',
        x: 0.20,
        y: 0.61,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 6,
        title: 'Number',
        x: 0.57,
        y: 0.55,
        status: LevelStatus.special,
        shape: LevelButtonShape.pill,
      ),
      LevelItem(
        number: 7,
        title: 'Number',
        x: 0.52,
        y: 0.47,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 8,
        title: 'Family',
        x: 0.80,
        y: 0.37,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 9,
        title: 'Greeting',
        x: 0.48,
        y: 0.32,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 10,
        title: 'Number',
        x: 0.75,
        y: 0.20,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 11,
        title: 'Number',
        x: 0.24,
        y: 0.11,
        status: LevelStatus.locked,
        showLock: true,
      ),
    ],
  ),
  MapData(
    background: 'assets/images/game_map/map_3.jpg',
    levels: [
      LevelItem(
        number: 1,
        title: 'Greeting',
        x: 0.84,
        y: 0.89,
        status: LevelStatus.completed,
        levelStar: LevelStar.excellent,
      ),
      LevelItem(
        number: 2,
        title: 'Number',
        x: 0.27,
        y: 0.87,
        status: LevelStatus.completed,
        levelStar: LevelStar.great,
      ),
      LevelItem(
        number: 3,
        title: 'Number',
        x: 0.68,
        y: 0.83,
        status: LevelStatus.completed,
        levelStar: LevelStar.good,
      ),
      LevelItem(
        number: 4,
        title: 'Family',
        x: 0.38,
        y: 0.75,
        status: LevelStatus.unlocked,
      ),
      LevelItem(
        number: 5,
        title: 'Greeting',
        x: 0.80,
        y: 0.70,
        status: LevelStatus.special,
        shape: LevelButtonShape.pill,
      ),
      LevelItem(
        number: 6,
        title: 'Number',
        x: 0.27,
        y: 0.63,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 7,
        title: 'Number',
        x: 0.75,
        y: 0.60,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 8,
        title: 'Family',
        x: 0.52,
        y: 0.535,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 9,
        title: 'Greeting',
        x: 0.83,
        y: 0.495,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 10,
        title: 'Number',
        x: 0.30,
        y: 0.465,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 11,
        title: 'Number',
        x: 0.80,
        y: 0.38,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 12,
        title: 'Greeting',
        x: 0.42,
        y: 0.35,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 13,
        title: 'Number',
        x: 0.70,
        y: 0.28,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 14,
        title: 'Number',
        x: 0.25,
        y: 0.25,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 15,
        title: 'Family',
        x: 0.65,
        y: 0.20,
        shape: LevelButtonShape.pill,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 16,
        title: 'Greeting',
        x: 0.20,
        y: 0.14,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 17,
        title: 'Number',
        x: 0.50,
        y: 0.09,
        status: LevelStatus.locked,
        showLock: true,
      ),
    ],
  ),
  MapData(
    background: 'assets/images/game_map/map_4.jpg',
    levels: [
      LevelItem(
        number: 1,
        title: 'Greeting',
        x: 0.31,
        y: 0.90,
        status: LevelStatus.completed,
        levelStar: LevelStar.excellent,
      ),
      LevelItem(
        number: 2,
        title: 'Number',
        x: 0.67,
        y: 0.88,
        status: LevelStatus.completed,
        levelStar: LevelStar.great,
      ),
      LevelItem(
        number: 3,
        title: 'Number',
        x: 0.30,
        y: 0.80,
        status: LevelStatus.completed,
        levelStar: LevelStar.good,
      ),
      LevelItem(
        number: 4,
        title: 'Family',
        x: 0.38,
        y: 0.74,
        status: LevelStatus.unlocked,
      ),
      LevelItem(
        number: 5,
        title: 'Greeting',
        x: 0.70,
        y: 0.70,
        status: LevelStatus.special,
        shape: LevelButtonShape.pill,
      ),
      LevelItem(
        number: 6,
        title: 'Number',
        x: 0.15,
        y: 0.63,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 7,
        title: 'Number',
        x: 0.85,
        y: 0.575,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 8,
        title: 'Family',
        x: 0.42,
        y: 0.535,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 9,
        title: 'Greeting',
        x: 0.45,
        y: 0.43,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 10,
        title: 'Number',
        x: 0.30,
        y: 0.385,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 11,
        title: 'Number',
        x: 0.50,
        y: 0.34,
        shape: LevelButtonShape.roundedSquare,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 12,
        title: 'Greeting',
        x: 0.25,
        y: 0.25,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 13,
        title: 'Number',
        x: 0.65,
        y: 0.22,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 14,
        title: 'Number',
        x: 0.20,
        y: 0.155,
        shape: LevelButtonShape.pill,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 15,
        title: 'Family',
        x: 0.75,
        y: 0.11,
        status: LevelStatus.locked,
        showLock: true,
      ),
      LevelItem(
        number: 16,
        title: 'Greeting',
        x: 0.25,
        y: 0.06,
        status: LevelStatus.locked,
        showLock: true,
      ),
    ],
  ),
  MapData(
    background: 'assets/images/game_map/map_5.jpg',
    levels: [],
  ),
  MapData(
    background: 'assets/images/game_map/map_6.jpg',
    levels: [],
  ),
  MapData(
    background: 'assets/images/game_map/map_7.jpg',
    levels: [],
  ),
];