// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJrlePoOHzkUKmuH8oD0kBHsekjXu1BI',
    appId: '1:665447157898:android:e7322907e37aed0aca5d73',
    messagingSenderId: '665447157898',
    projectId: 'terraproc-b628a',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJrlePoOHzkUKmuH8oD0kBHsekjXu1BI',
    appId: '1:665447157898:android:e7322907e37aed0aca5d73',
    messagingSenderId: '665447157898',
    projectId: 'terraproc-b628a',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdH9oTZKp3pibpEtrNqi20mfhCpo3i04',
    appId: '1:665447157898:ios:1a8d241eb9fe5ac9ca5d73',
    messagingSenderId: '665447157898',
    projectId: 'terraproc-b628a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJrlePoOHzkUKmuH8oD0kBHsekjXu1BI',
    appId: '1:665447157898:android:e7322907e37aed0aca5d73',
    messagingSenderId: '665447157898',
    projectId: 'terraproc-b628a',
  );
}